
 (kb::write-file-start) 
 (kb::write-qreg-type-binding-statement :|@#_x| :|_#_:TYPE-DECL| :|@__int|) 
 (kb::write-s0-expression :|_=_generic| :|@%_let_num| :|^->0-1|) 
 (kb::enter-nested-form :|^<-0-1|) 
 (kb::prepare-expression :|_%_:lc-f| :|@%_+| :|#__u32| :|###23| :|#__u32| :|###4|) 
 (kb::leave-nested-form) 
 (kb::write-promote-type-binding-expression :|@#_x|) 
 (kb::write-cmd-eval) 
 (kb::write-statement-clear) 
 (kb::write-s0-expression :|_=_generic| :|@%_prn| :|@#_x|) 
 (kb::write-promote-expression) 
 (kb::write-cmd-eval) 
 (kb::write-statement-clear) 
 (kb::write-file-end)