
 (kb::write-file-start) 
 (kb::write-s0-expression :|_=_generic| :|@%_test-0-ss| :|#__str| "\"abcdef\"" :|#__str| "\"cd\"") 
 (kb::write-promote-expression) 
 (kb::write-cmd-eval) 
 (kb::write-statement-clear) 
 (kb::write-qreg-type-binding-statement :|@#_x2| :|_#_:TYPE-DECL| :|@__str|) 
 (kb::write-s0-expression :|_=_generic| :|@%_test-s-ss| :|#__str| "\"abcdef\"" :|#__str| "\"cd\"") 
 (kb::write-promote-type-binding-expression :|@#_x2|) 
 (kb::write-cmd-eval) 
 (kb::write-statement-clear) 
 (kb::write-s0-expression :|_=_generic| :|@%_prs| :|@#_x2|) 
 (kb::write-promote-expression) 
 (kb::write-cmd-eval) 
 (kb::write-statement-clear) 
 (kb::write-qreg-type-binding-statement :|@#_x3| :|_#_:TYPE-DECL| :|@__int|) 
 (kb::write-s0-expression :|_=_generic| :|@%_test-i-ss| :|#__str| "\"abcdef\"" :|#__str| "\"cd\"") 
 (kb::write-promote-type-binding-expression :|@#_x3|) 
 (kb::write-cmd-eval) 
 (kb::write-statement-clear) 
 (kb::write-s0-expression :|_=_generic| :|@%_prn| :|@#_x3|) 
 (kb::write-promote-expression) 
 (kb::write-cmd-eval) 
 (kb::write-statement-clear) 
 (kb::write-s0-expression :|_=_generic| :|@%_test-0-s| :|#__str| "\"abcdef\"") 
 (kb::write-promote-expression) 
 (kb::write-cmd-eval) 
 (kb::write-statement-clear) 
 (kb::write-qreg-type-binding-statement :|@#_x5| :|_#_:TYPE-DECL| :|@__str|) 
 (kb::write-s0-expression :|_=_generic| :|@%_test-s-s| :|#__str| "\"abcdef\"") 
 (kb::write-promote-type-binding-expression :|@#_x5|) 
 (kb::write-cmd-eval) 
 (kb::write-statement-clear) 
 (kb::write-s0-expression :|_=_generic| :|@%_prs| :|@#_x5|) 
 (kb::write-promote-expression) 
 (kb::write-cmd-eval) 
 (kb::write-statement-clear) 
 (kb::write-qreg-type-binding-statement :|@#_x6| :|_#_:TYPE-DECL| :|@__int|) 
 (kb::write-s0-expression :|_=_generic| :|@%_test-i-s| :|#__str| "\"abcdef\"") 
 (kb::write-promote-type-binding-expression :|@#_x6|) 
 (kb::write-cmd-eval) 
 (kb::write-statement-clear) 
 (kb::write-s0-expression :|_=_generic| :|@%_prn| :|@#_x6|) 
 (kb::write-promote-expression) 
 (kb::write-cmd-eval) 
 (kb::write-statement-clear) 
 (kb::write-qreg-type-binding-statement :|@#_fnd| :|_#_:TYPE-DECL| :|@__Fn_Doc*|) 
 (kb::symbol-init-via-type :|@#_fnd|) 
 (kb::write-promote-expression) 
 (kb::write-cmd-eval) 
 (kb::write-statement-clear) 
 (kb::write-qreg-type-binding-statement :|@#_kenv| :|_#_:TYPE-DECL| :|@__KCM_Env*|) 
 (kb::write-s0-expression :|_=_generic| :|@%_envv| :|#__str| "\"KCM_Env*\"") 
 (kb::write-promote-type-binding-expression :|@#_kenv|) 
 (kb::write-cmd-eval) 
 (kb::write-statement-clear) 
 (kb::write-s1-expression :|%%_init| :|@@_fnd| :|@#_kenv|) 
 (kb::write-promote-expression) 
 (kb::write-cmd-eval) 
 (kb::write-statement-clear) 
 (kb::write-s1-expression :|%%_test-0-S10-s| :|@@_fnd| :|#__str| "\"abcd\"") 
 (kb::write-promote-expression) 
 (kb::write-cmd-eval) 
 (kb::write-statement-clear) 
 (kb::write-qreg-type-binding-statement :|@#_fnd| :|_#_:TYPE-DECL| :|@__Fn_Doc*|) 
 (kb::symbol-init-via-type :|@#_fnd|) 
 (kb::write-promote-expression) 
 (kb::write-cmd-eval) 
 (kb::write-statement-clear) 
 (kb::write-qreg-type-binding-statement :|@#_kenv| :|_#_:TYPE-DECL| :|@__KCM_Env*|) 
 (kb::write-s0-expression :|_=_generic| :|@%_envv| :|#__str| "\"KCM_Env*\"") 
 (kb::write-promote-type-binding-expression :|@#_kenv|) 
 (kb::write-cmd-eval) 
 (kb::write-statement-clear) 
 (kb::write-s1-expression :|%%_init| :|@@_fnd| :|@#_kenv|) 
 (kb::write-promote-expression) 
 (kb::write-cmd-eval) 
 (kb::write-statement-clear) 
 (kb::write-s1-expression :|%%_test-0-S10| :|@@_fnd|) 
 (kb::write-promote-expression) 
 (kb::write-cmd-eval) 
 (kb::write-statement-clear) 
 (kb::write-file-end)